name: Build PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile XeLaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tex/document.tex
          latexmk_use_xelatex: true

      - name: List generated files
        run: |
          find . -name "*.pdf"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdf
          path: |
            **/*.pdf
